name: Neuromotor CI

on:
  push:

jobs:
  linux-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        auto-update-conda: true
        python-version: "3.12"
        miniconda-version: "latest"
        activate-environment: neuromotor
        environment-file: environment.yml

    - name: Install local package
      shell: bash -el {0}
      run: |
        conda activate neuromotor
        pip install -e .

    - name: Run pre-commit checks
      shell: bash -el {0}
      run: |
        conda activate neuromotor
        pre-commit run --all-files

    - name: Lint with flake8
      shell: bash -el {0}
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run unit tests
      shell: bash -el {0}
      run: |
        conda activate neuromotor
        pytest

    - name: Run integration tests (cpu, dummy data)
      shell: bash -el {0}
      run: |
        conda activate neuromotor
        pytest \
          -m 'integration and not real_data and not full_data and not cuda and not real_checkpoints' \
          -vv \
          --durations=10 \
          -rA
